## 4.1 전치 행렬

### 4.1.1 전치 행렬의 개념

전치 행렬의 크기는 기존 행렬의 행의 크기 및 열의 크기와 반대  

### 4.1.2 전치 행렬의 성질

### 4.1.3 파이썬 실습

In [ ]:
def transpose(A):
    """
    행렬의 전치 행렬
    입력값: 전치 행렬을 구하고자 하는 행렬 A
    출력값: 행렬 A의 전치 행렬 At
    """
    
    n = len(A)
    p = len(A[0])
    
    At = []
    for i in range(0, p):
        row = []
        for j in range(0, n):
            val = A[j][i]
            row.append(val)
        At.append(row)
    return At


### 4.1.4 넘파이 실습

`np.transpose()` 혹은  
`.T` 메서드  


## 4.2 대칭 행렬

### 4.2.1 대칭 행렬의 개념

**대칭 행렬**: 기존 행렬과 전치 행렬이 동일한 정사각 행렬, $A=A^T$

### 4.2.2 대칭 행렬의 성질

대칭 행렬 간 덧셈이나 뺄셈의 결과는 대칭 행렬  
대칭 행렬끼리 행렬 곱을 한 결과는 반드시 대칭 행렬은 아님  
행렬 A가 대칭 행렬일 때 대칭 행렬 A의 거듭 제곱 형태도 대칭 행렬  
어떤 행렬 A가 존재할 때 자기 자신의 전치 행렬을 곱한 결과는 대칭 행렬이 됨 (곱하는 순서를 바꾸어도 값은 다르지만 대칭 행렬)  

### 4.2.3 파이썬 실습

NOTE: 앞에서 구현한 transpose(), matmul() 함수로 확인 가능

### 4.2.4 넘파이 실습

`np.transpose()`, `np.matmul()` 함수로 확인 가능

## 4.3 대각 행렬

### 4.3.1 대각 행렬의 개념

대각 행렬은 행렬의 주 대각 원소가 아닌 원소가 0인 정사각 행렬  
행 번호와 열 번호가 동일한 원소를 주 대각 원소라고 부름  

NOTE: GOTO Chapter 7. 역행렬  

대각 행렬의 역행렬: 주 대각 원소의 역수  
대각 행렬의 거듭 제곱: 대각 원소의 거듭 제곱  

### 4.3.2 대각 행렬의 성질

어떤 행렬에 대각 행렬을 곱할 때, 대각 행렬을 오른쪽에 곱하는 경우, 기존 행렬의 **열** 값이 대각 원소의 배수가 되며,  
대각 행렬을 왼쪽에 곱하는 경우 기존 행렬의 **행** 값이 대각 원소의 배수가 되는 것을 확인할 수 있음

### 4.3.3 파이썬 실습

#### 대각 행렬 구하기

대각 행렬을 구한다는 것은 대각 원소를 제외한 나머지 원소를 0으로 바꾸는 것을 의미  


In [ ]:
def diag(A):
    """
    행렬의 대각 행렬
    입력값: 대각 행렬을 구하고자 하는 행렬 A
    출력값: 행렬 A의 대각 행렬 D
    """
    
    n = len(A)
    D= []
    for i in range(0, n):
        row = []
        for j in range(0, n):
            if i==j:
                row.append(A[i][j])
            else:
                row.append(0)
        D.append(row)
    return D


#### 대각 원소 구하기

주어진 행렬의 대각 원소를 추출해 보기  

In [ ]:
def diag_ele(A):
    """
    대각 원소 구하기
    입력값: 대각 원소를 구하고자 하는 행렬 A
    출력값: 행렬 A의 대각 원소 리스트 d
    """
    
    n = len(A)
    d = []
    for i in range(0, n):
        d.append(A[i][i])
    return d


#### 대각 원소가 주어졌을 때, 대각 행렬로 변환

대각 원소가 주어졌을 때 대각 행렬을 만들 수 있는 함수 구현

#### 일반 행렬에 대각 행렬을 곱했을 때

### 4.3.4 넘파이 실습

`np.diag()`


In [ ]:
def ele2diag(a):
    """
    대각 원소 -> 대각 행렬 변환
    입력값: 대각 원소 리스트 a
    출력값: 대각 원소 a를 이용해 생성한 n*n 대각 행렬 D
    """
    
    n = len(a)
    D = []
    for i in range(0, n):
        row = []
        for j in range(0, n):
            if i==j:
                row.append(a[i])
            else:
                row.append(0)
        D.append(row)
    return D

## 4.4 단위 행렬

### 4.4.1 단위 행렬의 개념

단위 행렬: 주 대각 원소가 1이고 그 밖의 나머지 원소는 모두 0인 대각 행렬

### 4.4.2 단위 행렬의 성질

행렬 곱 위치와 상관없이 기존 행렬에 단위 행렬을 곱한 결과는 기존 행렬과 동일하다.
$$\mathbf{AI}=\mathbf{IA}=\mathbf{A}$$

### 4.4.3 파이썬 실습

단위 행렬을 생성하는 함수  

### 4.4.4 넘파이 실습

`np.identity()`


In [ ]:
def identity(n):
    """
    단위 행렬 생성
    입력값: 단위 행렬의 크기 n
    출력값: n*n 단위 행렬 I
    """
    
    I = []
    for i in range(0, n):
        row = []
        for j in range(0, n):
            if i==j:
                row.append(1)
            else:
                row.append(0)
        I.append(row)
    return I

## 4.5 영 행렬

### 4.5.1 영 행렬의 개념

행렬 구성 원솩 모두 0일 때 주로 $\mathbf{0}$으로 표시  

### 4.5.2 영 행렬의 성질

임의의 행렬에 영 행렬을 더하거나 뺀 결과는 기존 행렬과 동일  
기존 행렬에 영행렬을 곱하면 결과는 영 행렬이 됨  

### 4.5.3 파이썬 실습

n*p인 영 행렬을 만드는 함수 구현  

In [ ]:
def zero_mat(n, p):
    """
    영 행렬 생성
    입력값: 생성하고자 할 영 행렬의 크기 n행, p열
    출력값: n*p 영 행렬 Z
    """
    
    Z = []
    for i in range(0, n):
        row = []
        for j in range(0, p):
            row.append(0)
        Z.append(row)
    return Z

## 4.6 삼각 행렬

### 4.6.1 삼각 행렬의 개념

**상 삼각 행렬**: 주 대각 원소 아래쪽에 있는 모든 원소가 0인 정사각 행렬  
**하 삼각 행렬**: 주 대각 원소 위쪽에 있는 모든 원소가 0인 정사각 행렬

### 4.6.2 삼각 행렬의 성질

삼각 행렬 간 덧셈, 뺄셈, 행렬 곱의 결과는 삼각 행렬  
상 삼각 행렬의 전치 행렬은 하 삼각 행렬, 역도 성립  
삼각 행렬의 역행렬도 삼각 행렬

### 4.6.3 파이썬 실습

`np.triu()`: 상 삼각 행렬  
`np.tril()`: 하 삼각 행렬

In [ ]:
def u_tri(A):
    """
    상 삼각 행렬 변환
    입력값: 상 삼각 행렬로 변환하고자 하는 행렬 A
    출력값: 행렬 A를 상 삼각 행렬로 변환시킨 행렬 utri
    """
    
    n = len(A)
    p = len(A[0])
    utri = []
    
    for i in range(0, n):
        row = []
        for j in range(0, p):
            if i>j:
                row.append(0)
            else:
                row.append(A[i][j])
        utri.append(row)
    return utri

def l_tri(A):
    """
    하 삼각 행렬 변환
    입력값: 하 삼각 행렬로 변환하고자 하는 행렬 A
    출력값: 행렬 A를 하 삼각 행렬로 변환시킨 행렬 ltri
    """
    
    n = len(A)
    p = len(A[0])
    ltri = []
    
    for i in range(0, n):
        row = []
        for j in range(0, p):
            if i<j:
                row.append(0)
            else:
                row.append(A[i][j])
        ltri.append(row)
    return ltri

## 4.7 토플리츠 행렬

### 4.7.1 토플리츠 행렬의 개념

1행의 원소가 오른쪽으로 한 칸씩 이동,  
가장 왼쪽 원소로 1행 원소에 속하지 않는 새로운 원소를 채움  
시계열 분석 시 자주 사용됨

### 4.7.2 파이썬 실습


In [ ]:
def toeplitz(a, b):
    """
    토플리츠 행렬 변환
    입력값: 토플리츠 행렬로 변환하고자 하는 리스트 a, b
    출력값: 리스트 a, b를 이용해 만든 토플리츠 행렬 A
    """
    
    n1 = len(a)
    n2 = len(b)
    A = []
    for i in range(0, n1):
        row = []
        for j in range(0, n2):
            if i>j:
                row.append(a[i-j])
            else:
                row.append(b[j-1])
        A.append(row)
    return A


### 4.7.3 scipy 실습

*Reference)* numpy는 지원하지 않는다.

In [ ]:
from scipy.linalg import toeplitz

## 4.8 이중 대각 행렬

### 4.8.1 이중 대각 행렬의 개념

대각 원소의 바로 위쪽 혹은 아래쪽 원소가 0이 아닌 행렬

### 4.8.2 파이썬 실습

In [1]:
# upper bidiagonal matrix
def u_bidiag(A):
    """
    uppder bidiagonal 행렬
    입력값: 행렬 A
    출력값: 행렬 A의 upper bidiagonal 행렬 res
    """
    n = len(A)
    p = len(A[0])
    
    res = []
    for i in range(0, n):
        row = []
        for j in range(0, p):
            if i > j or j-i > 1:
                row.append(0)
            else:
                row.append(A[i][j])
        res.append(row)
    return res

In [2]:
# lower bidiagonal matrix
def l_bidiag(A):
    """
    lower bidiagonal 행렬
    입력값: 행렬 A
    출력값: 행렬 A의 lower bidiagonal 행렬 res
    """
    n = len(A)
    p = len(A[0])
    
    res = []
    for i in range(0, n):
        row = []
        for j in range(0, p):
            if i < j or i-j > 1:
                row.append(0)
            else:
                row.append(A[i][j])
        res.append(row)
    return res

### 4.8.3 넘파이 실습

In [3]:
import numpy as np
A = np.array([[1, 2, 1, 3], [5, 3, 4, 1], [2, 1, 7, 9], [2, 8, 1, 3]])
# 대각 행렬 원소 구하기
diag_ele = np.diag(A)
# 원소를 바탕으로 대각행렬 만들기
np.diag(diag_ele)

# 대각 행렬보다 위쪽에 존재하는 원소
u_diag_ele = np.diag(A, k=1)

# 위의 원소로 행렬을 만듦
np.diag(u_diag_ele, k=1) # k < 0이면 대각 원소보다 아래줄의 원소를 구함 - lower bidiagonal에서 -1

# 두 대각 행렬을 더함
u_diag = np.diag(diag_ele) + np.diag(u_diag_ele, k=1)
print(u_diag)

[[1 2 0 0]
 [0 3 4 0]
 [0 0 7 9]
 [0 0 0 3]]


## 4.9 하우스홀더 행렬

### 4.9.1 하우스홀더 행렬의 개념

어떤 행렬을 다른 형태로 변환할 때 사용  
정사각 행렬이며, 모든 열이 `정규 직교`한다.
$$\mathbf{H} = \mathbf{I} - 2\frac{\mathbf{vv}^T}{\mathbf{v}^T\mathbf{v}}$$

### 4.9.2 파이썬 실습

NOTE: 벡터의 외적 - GOTO Chapter 10  
NOTE: 벡터의 내적 - GOTO Chapter 9

In [4]:
# 벡터의 외적
def outer_product(a, b):
    """
    벡터의 외적
    입력값: 외적할 벡터 리스트 a, b
    출력값: 벡터 a, b의 외적 결과 res
    """
    res = []
    n1 = len(a)
    n2 = len(b)
    for i in range(0, n1):
        row = []
        for j in range(0, n2):
            val = a[i] * b[j]
            row.append(val)
        res.append(row)
    return res

In [5]:
# 벡터의 내적
def inner_product(a, b):
    """
    벡터의 내적
    입력값: 내적할 벡터 리스트 a, b
    출력값: 벡터 a, b의 내적 결과 res
    """
    n = len(a)
    res = 0
    for i in range(0, n):
        res += a[i] * b[i]
    return res

In [7]:
# 행렬의 뺄셈
def subtract(A, B):
    """
    행렬의 뺄셈
    입력값: 행렬의 뺄셈을 수행할 행렬 A, B
    출력값: 행렬 A와 행렬 B의 뺄셈 결과인 행렬 C
    """
    
    n = len(A)
    p = len(A[0])
    
    res = []
    for i in range(0, n):
        row = []
        for j in range(0, p):
            val = A[i][j] - B[i][j]
            row.append(val)
        res.append(row)
    return res

$$\mathbf{V}=2\frac{\mathbf{vv}^T}{\mathbf{v}^T\mathbf{v}}$$

In [8]:
# 위의 행렬 V 구현
def householder(v):
    """
    하우스홀더 행렬
    입력값: 하우스홀더 행렬을 생성할 리스트 v
    출력값: 리스트 v를 이용해 생성한 하우스홀더 행렬 H
    """
    n = len(v)
    outer_mat = outer_product(v, v)
    inner_val = inner_product(v, v)
    V = []
    for i in range(0, n):
        row = []
        for j in range(0, n):
            val = (2/inner_val)*outer_mat[i][j]
            row.append(val)
        V.append(row)
    H = subtract(identity(n), V)
    return H

### 4.9.3 넘파이 실습

`np.outer()`: 벡터의 외적으로 행렬을 만듦  
`np.inner()`: 내적으로 값을 구함  
`np.identity()`: 단위 행렬  
각 자 구해서 조합하여 구함

In [10]:
import numpy as np

v = np.array([1, 0, 2, 3])

n = len(v)

outer_mat = np.outer(v, v)
inner_val = np.inner(v, v)
I = np.identity(n)

H = I - (2/inner_val) * outer_mat
print(H)

[[ 0.85714286  0.         -0.28571429 -0.42857143]
 [ 0.          1.          0.          0.        ]
 [-0.28571429  0.          0.42857143 -0.85714286]
 [-0.42857143  0.         -0.85714286 -0.28571429]]
